-- Migración: crear tablas bonos y bono_items

CREATE TABLE IF NOT EXISTS `bonos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `afiliado_id` INT NOT NULL,
  `fecha` DATE NOT NULL DEFAULT CURRENT_DATE,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `bono_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `bono_id` INT NOT NULL,
  `practica_id` INT NULL,
  `descripcion` VARCHAR(255) NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`bono_id`) REFERENCES `bonos`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
